/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 06:59:47 GMT 2022
 */

package com.thealgorithms.dynamicprogramming;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.dynamicprogramming.LongestPalindromicSubsequence;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LongestPalindromicSubsequence_ESTest extends LongestPalindromicSubsequence_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LongestPalindromicSubsequence longestPalindromicSubsequence0 = new LongestPalindromicSubsequence();
      // Undeclared exception!
      try { 
        LongestPalindromicSubsequence.LPS((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[2];
      String string0 = "(C7X";
      stringArray0[0] = "(C7X";
      String string1 = "";
      stringArray0[1] = "";
      LongestPalindromicSubsequence.main(stringArray0);
      LongestPalindromicSubsequence.main(stringArray0);
      LongestPalindromicSubsequence longestPalindromicSubsequence0 = new LongestPalindromicSubsequence();
      LongestPalindromicSubsequence.LPS("");
      LongestPalindromicSubsequence.main(stringArray0);
      LongestPalindromicSubsequence.main(stringArray0);
      LongestPalindromicSubsequence.main(stringArray0);
      LongestPalindromicSubsequence.main(stringArray0);
      LongestPalindromicSubsequence.LPS("");
      LongestPalindromicSubsequence.main(stringArray0);
      // Undeclared exception!
      LongestPalindromicSubsequence.LPS("ANxe>,Os\"V B");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LongestPalindromicSubsequence longestPalindromicSubsequence0 = new LongestPalindromicSubsequence();
      assertNotNull(longestPalindromicSubsequence0);
      
      LongestPalindromicSubsequence.main((String[]) null);
      // Undeclared exception!
      LongestPalindromicSubsequence.LPS(")xlCD\fl'QsI4-");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = LongestPalindromicSubsequence.LPS("");
      assertEquals("", string0);
      assertNotNull(string0);
      
      LongestPalindromicSubsequence longestPalindromicSubsequence0 = new LongestPalindromicSubsequence();
      assertNotNull(longestPalindromicSubsequence0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LongestPalindromicSubsequence longestPalindromicSubsequence0 = new LongestPalindromicSubsequence();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "BBABCBCAB";
      stringArray0[3] = "";
      stringArray0[4] = "W8!#";
      stringArray0[5] = "";
      stringArray0[6] = "ILLU1OQo^B";
      stringArray0[7] = "=c;X9ng$L`R2|Z^";
      LongestPalindromicSubsequence.main(stringArray0);
      // Undeclared exception!
      try { 
        LongestPalindromicSubsequence.LPS((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LongestPalindromicSubsequence.LPS("f");
      String[] stringArray0 = new String[3];
      stringArray0[0] = "f";
      stringArray0[1] = "f";
      stringArray0[2] = "f";
      LongestPalindromicSubsequence.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }
}
