/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 03:24:59 GMT 2022
 */

package com.thealgorithms.dynamicprogramming;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.dynamicprogramming.RegexMatching;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegexMatching_ESTest extends RegexMatching_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int[][] intArray0 = new int[8][7];
      boolean boolean0 = RegexMatching.regexRecursion("&YgZx;SwQfQ;L!o", "MH'n]", 0, 0, intArray0);
      assertFalse(boolean0);
      assertEquals(8, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[][] intArray0 = new int[4][3];
      int[] intArray1 = new int[1];
      intArray1[0] = 2;
      intArray0[2] = intArray1;
      boolean boolean0 = RegexMatching.regexRecursion("Method 2: ", "Method 2: ", 2, 0, intArray0);
      assertTrue(boolean0);
      assertEquals(4, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[][] intArray0 = new int[8][0];
      int[] intArray1 = new int[6];
      intArray1[4] = (-1);
      intArray0[4] = intArray1;
      boolean boolean0 = RegexMatching.regexRecursion("q}q&Y-B~Ob*'ux[", "aagvCi!$aFx8_dQqZZ", 4, 4, intArray0);
      assertTrue(boolean0);
      assertEquals(8, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[][] intArray0 = new int[0][3];
      boolean boolean0 = RegexMatching.regexRecursion("", "\u0005${X~2UHbg5IrWW", 0, 2, intArray0);
      assertFalse(boolean0);
      assertEquals(0, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        RegexMatching.regexRecursion("", ">3dW%}W", 727, 727, (int[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.dynamicprogramming.RegexMatching", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[][] intArray0 = new int[3][7];
      boolean boolean0 = RegexMatching.regexRecursion("", "", 0, 2549, intArray0);
      assertTrue(boolean0);
      assertEquals(3, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[][] intArray0 = new int[4][5];
      boolean boolean0 = RegexMatching.regexRecursion("6N", "", 404, 0, intArray0);
      assertFalse(boolean0);
      assertEquals(4, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("<F65Vd94o+NR5O", "*9UluX8XJF", 0, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("", "%8", 0, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        RegexMatching.regexRecursion("", "XY({", 1356, (-2714));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("", "", 0, 1356);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("Method 1: ", "", 943, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("", "')P?,N1L$xW4;@");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int[][] intArray0 = new int[7][7];
      // Undeclared exception!
      try { 
        RegexMatching.regexRecursion("", "", 0, (-1010), intArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      int[][] intArray0 = new int[1][9];
      int[] intArray1 = new int[0];
      intArray0[0] = intArray1;
      // Undeclared exception!
      try { 
        RegexMatching.regexRecursion("Method 2: ", "$U;ohzJf +VqXI", 0, 0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("com.thealgorithms.dynamicprogramming.RegexMatching", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        RegexMatching.regexRecursion("", "Method 1: ", (-734), 943);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        RegexMatching.regexRecursion((String) null, (String) null, 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.dynamicprogramming.RegexMatching", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        RegexMatching.regexRecursion("98}wjx!O", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.dynamicprogramming.RegexMatching", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      // Undeclared exception!
      try { 
        RegexMatching.regexBU("", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.dynamicprogramming.RegexMatching", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("x!*]-nG|_[Ju8*?c", "?Zn~EnN!6# ", 0, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = new String[4];
      RegexMatching.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexBU("r6}6GOX*TT>$im/", "r6}6GOX*TT>$im/");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexBU("wQ", "cE?~-h");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      int[][] intArray0 = new int[5][0];
      int[] intArray1 = new int[6];
      intArray1[3] = 2;
      intArray0[2] = intArray1;
      intArray0[3] = intArray1;
      boolean boolean0 = RegexMatching.regexRecursion("BP0Lhc", "BP0Lhc", 2, 2, intArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      int[][] intArray0 = new int[3][2];
      RegexMatching.regexRecursion("{tpWI1*3nZ", "?1ns=u^lRcf_D~NN", 0, 0, intArray0);
      boolean boolean0 = RegexMatching.regexRecursion("gA_u?_", "gA_u?_", 0, 0, intArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      int[][] intArray0 = new int[0][3];
      boolean boolean0 = RegexMatching.regexRecursion("", "*D:3v.e^TOeD~", 0, 0, intArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      int[][] intArray0 = new int[2][9];
      boolean boolean0 = RegexMatching.regexRecursion("", "", 0, 0, intArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("Method --2: ", "? }gzAtE", 0, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("Method 3: ", "Method 3: ", 0, 0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("')P?,N1L$xW4;@", "*D:3v.e^TOeD~");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("Method --2: ", "? }gzAtE");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      boolean boolean0 = RegexMatching.regexRecursion("r6}6GOX*TT>$im/", "r6}6GOX*TT>$im/");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      RegexMatching regexMatching0 = new RegexMatching();
  }
}
