/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 04:49:25 GMT 2022
 */

package com.thealgorithms.dynamicprogramming;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.dynamicprogramming.SubsetSum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SubsetSum_ESTest extends SubsetSum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "";
      String string0 = "";
      stringArray0[1] = "";
      SubsetSum.main(stringArray0);
      SubsetSum.main(stringArray0);
      SubsetSum subsetSum0 = new SubsetSum();
      SubsetSum.main(stringArray0);
      SubsetSum.main(stringArray0);
      SubsetSum.main(stringArray0);
      SubsetSum.main(stringArray0);
      SubsetSum.main(stringArray0);
      SubsetSum.main(stringArray0);
      SubsetSum.main(stringArray0);
      SubsetSum.main(stringArray0);
      SubsetSum.main(stringArray0);
      // Undeclared exception!
      SubsetSum.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubsetSum subsetSum0 = new SubsetSum();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "";
      SubsetSum.main(stringArray0);
      String[] stringArray1 = new String[5];
      stringArray1[0] = "";
      stringArray1[1] = "";
      stringArray1[2] = "";
      stringArray1[3] = "5?=x&3E:Y";
      stringArray1[4] = "";
      SubsetSum.main(stringArray1);
      assertEquals(5, stringArray1.length);
  }
}
