/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 05:40:58 GMT 2022
 */

package com.thealgorithms.dynamicprogramming;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.dynamicprogramming.FordFulkerson;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FordFulkerson_ESTest extends FordFulkerson_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[37];
      FordFulkerson.main(stringArray0);
      assertEquals(37, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FordFulkerson fordFulkerson0 = new FordFulkerson();
  }
}
