/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 05:38:29 GMT 2022
 */

package com.thealgorithms.dynamicprogramming;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.dynamicprogramming.LongestValidParentheses;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LongestValidParentheses_ESTest extends LongestValidParentheses_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = "PXGz\\u[i=P} e4a*%)";
      SystemInUtil.addInputLine(string0);
      // Undeclared exception!
      try { 
        LongestValidParentheses.main((String[]) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int int0 = LongestValidParentheses.getLongestValidParentheses("!))");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = LongestValidParentheses.getLongestValidParentheses("O!(<Lh;~9h;\",,");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = LongestValidParentheses.getLongestValidParentheses("}l");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = LongestValidParentheses.getLongestValidParentheses("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SystemInUtil.addInputLine("quit");
      String[] stringArray0 = new String[0];
      LongestValidParentheses.main(stringArray0);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = LongestValidParentheses.getLongestValidParentheses("())[?jo");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = LongestValidParentheses.getLongestValidParentheses("3)x:0h");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int int0 = LongestValidParentheses.getLongestValidParentheses("Rzkus0()Sp1,:M)rmB");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = LongestValidParentheses.getLongestValidParentheses((String) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LongestValidParentheses longestValidParentheses0 = new LongestValidParentheses();
  }
}
