/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 06:29:56 GMT 2022
 */

package com.thealgorithms.dynamicprogramming;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.dynamicprogramming.MatrixChainRecursiveTopDownMemoisation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MatrixChainRecursiveTopDownMemoisation_ESTest extends MatrixChainRecursiveTopDownMemoisation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int[] intArray0 = new int[5];
      MatrixChainRecursiveTopDownMemoisation.Memoized_Matrix_Chain(intArray0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[0] = (-1198);
      intArray0[1] = (-1821);
      intArray0[2] = (-1133);
      MatrixChainRecursiveTopDownMemoisation.Memoized_Matrix_Chain(intArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[0] = (-1);
      intArray0[1] = (-434);
      intArray0[2] = (-3912);
      MatrixChainRecursiveTopDownMemoisation.Memoized_Matrix_Chain(intArray0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[][] intArray0 = new int[6][1];
      MatrixChainRecursiveTopDownMemoisation.Lookup_Chain(intArray0, intArray0[0], 0, 0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[][] intArray0 = new int[8][5];
      int[] intArray1 = new int[5];
      intArray1[1] = 2079;
      intArray0[5] = intArray1;
      MatrixChainRecursiveTopDownMemoisation.Lookup_Chain(intArray0, intArray1, 5, 1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[][] intArray0 = new int[3][7];
      int[] intArray1 = new int[4];
      intArray1[0] = (-1635);
      intArray0[1] = intArray1;
      MatrixChainRecursiveTopDownMemoisation.Lookup_Chain(intArray0, intArray0[0], 1, 0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        MatrixChainRecursiveTopDownMemoisation.Memoized_Matrix_Chain((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.dynamicprogramming.MatrixChainRecursiveTopDownMemoisation", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        MatrixChainRecursiveTopDownMemoisation.Memoized_Matrix_Chain(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("com.thealgorithms.dynamicprogramming.MatrixChainRecursiveTopDownMemoisation", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int[] intArray0 = new int[3];
      // Undeclared exception!
      try { 
        MatrixChainRecursiveTopDownMemoisation.Lookup_Chain((int[][]) null, intArray0, 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.dynamicprogramming.MatrixChainRecursiveTopDownMemoisation", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int[][] intArray0 = new int[9][9];
      // Undeclared exception!
      try { 
        MatrixChainRecursiveTopDownMemoisation.Lookup_Chain(intArray0, intArray0[4], (-1), 1598);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("com.thealgorithms.dynamicprogramming.MatrixChainRecursiveTopDownMemoisation", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MatrixChainRecursiveTopDownMemoisation.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MatrixChainRecursiveTopDownMemoisation matrixChainRecursiveTopDownMemoisation0 = new MatrixChainRecursiveTopDownMemoisation();
  }
}
