/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:32:21 GMT 2022
 */

package com.thealgorithms.dynamicprogramming;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.dynamicprogramming.RodCutting;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RodCutting_ESTest extends RodCutting_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RodCutting.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RodCutting rodCutting0 = new RodCutting();
  }
}
