/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 06:58:27 GMT 2022
 */

package com.thealgorithms.datastructures.trees;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.datastructures.trees.CreateBinaryTreeFromInorderPreorder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CreateBinaryTreeFromInorderPreorder_ESTest extends CreateBinaryTreeFromInorderPreorder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CreateBinaryTreeFromInorderPreorder createBinaryTreeFromInorderPreorder0 = new CreateBinaryTreeFromInorderPreorder();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[23];
      CreateBinaryTreeFromInorderPreorder.main(stringArray0);
      assertEquals(23, stringArray0.length);
  }
}
