/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:25:10 GMT 2022
 */

package com.thealgorithms.conversions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.conversions.HexToOct;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HexToOct_ESTest extends HexToOct_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("F$4t`G");
      String[] stringArray0 = new String[7];
      HexToOct.main(stringArray0);
      assertEquals(7, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = HexToOct.hex2decimal("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = HexToOct.hex2decimal("IzSYEV");
      assertEquals((-1118241), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = HexToOct.decimal2octal((-1));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = HexToOct.decimal2octal(746);
      assertEquals(1352, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        HexToOct.hex2decimal((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.conversions.HexToOct", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int int0 = HexToOct.decimal2octal(586142959);
      assertEquals((-155744373), int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int int0 = HexToOct.hex2decimal("d623;Gd5Y/");
      assertEquals(586142959, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      HexToOct hexToOct0 = new HexToOct();
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        HexToOct.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
