/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 05:42:03 GMT 2022
 */

package com.thealgorithms.datastructures.lists;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.datastructures.lists.SearchSinglyLinkedListRecursion;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SearchSinglyLinkedListRecursion_ESTest extends SearchSinglyLinkedListRecursion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SearchSinglyLinkedListRecursion searchSinglyLinkedListRecursion0 = new SearchSinglyLinkedListRecursion();
      searchSinglyLinkedListRecursion0.insertHead((-2182));
      boolean boolean0 = searchSinglyLinkedListRecursion0.search((-2182));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SearchSinglyLinkedListRecursion.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SearchSinglyLinkedListRecursion searchSinglyLinkedListRecursion0 = new SearchSinglyLinkedListRecursion();
      boolean boolean0 = searchSinglyLinkedListRecursion0.search((-2182));
      assertFalse(boolean0);
  }
}
