/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 06:09:07 GMT 2022
 */

package com.thealgorithms.datastructures.stacks;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.datastructures.stacks.LargestRectangle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LargestRectangle_ESTest extends LargestRectangle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        LargestRectangle.largestRectanglehistogram((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.datastructures.stacks.LargestRectangle", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[1] = 1;
      String string0 = LargestRectangle.largestRectanglehistogram(intArray0);
      assertEquals("1", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LargestRectangle.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LargestRectangle largestRectangle0 = new LargestRectangle();
  }
}
