/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 06:57:39 GMT 2022
 */

package com.thealgorithms.minimizinglateness;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.minimizinglateness.MinimizingLateness;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MinimizingLateness_ESTest extends MinimizingLateness_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[6];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("MinimizingLateness/lateness_data.txt");
      byte[] byteArray0 = new byte[1];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      // Undeclared exception!
      try { 
        MinimizingLateness.main(stringArray0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\u0000\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("MinimizingLateness/lateness_data.txt");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "-1");
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        MinimizingLateness.main(stringArray0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.minimizinglateness.MinimizingLateness", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("MinimizingLateness/lateness_data.txt");
      FileSystemHandling.shouldThrowIOException(evoSuiteFile0);
      String[] stringArray0 = new String[1];
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "9}+qX");
      try { 
        MinimizingLateness.main(stringArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[0];
      try { 
        MinimizingLateness.main(stringArray0);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[19];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("MinimizingLateness/lateness_data.txt");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "1");
      MinimizingLateness.main(stringArray0);
      assertEquals(19, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("MinimizingLateness/lateness_data.txt");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "1");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "1");
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        MinimizingLateness.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.StringTokenizer", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("MinimizingLateness/lateness_data.txt");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      String[] stringArray0 = new String[1];
      MinimizingLateness.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[4];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("MinimizingLateness/lateness_data.txt");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "8");
      // Undeclared exception!
      try { 
        MinimizingLateness.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.minimizinglateness.MinimizingLateness", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("MinimizingLateness/lateness_data.txt");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      MinimizingLateness.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      MinimizingLateness minimizingLateness0 = new MinimizingLateness();
  }
}
