/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 05:59:01 GMT 2022
 */

package com.thealgorithms.datastructures.lists;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.datastructures.lists.CreateAndDetectLoop;
import com.thealgorithms.datastructures.lists.Node;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CreateAndDetectLoop_ESTest extends CreateAndDetectLoop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Node node0 = new Node();
      Node node1 = new Node();
      node0.next = node0;
      Node node2 = new Node();
      CreateAndDetectLoop.detectLoop(node0);
      SystemInUtil.addInputLine("");
      node0.next.next = node2;
      node0.next.next = node1;
      CreateAndDetectLoop.detectLoop(node2);
      CreateAndDetectLoop.detectLoop(node0.next);
      node0.next.value = 1;
      CreateAndDetectLoop.createLoop(node2, 2);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CreateAndDetectLoop createAndDetectLoop0 = new CreateAndDetectLoop();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "com.thealgorithms.datastructures.lists.Node";
      stringArray0[1] = "~:";
      stringArray0[2] = "F$";
      stringArray0[3] = "WY~@W0J}{/Q";
      stringArray0[4] = "";
      stringArray0[5] = "";
      SystemInUtil.addInputLine("No loop found");
      stringArray0[6] = "F$";
      stringArray0[7] = "";
      stringArray0[8] = "";
      // Undeclared exception!
      try { 
        CreateAndDetectLoop.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CreateAndDetectLoop createAndDetectLoop0 = new CreateAndDetectLoop();
      int int0 = 3339;
      Node node0 = new Node(3339);
      node0.value = 0;
      CreateAndDetectLoop.detectLoop(node0);
      // Undeclared exception!
      try { 
        CreateAndDetectLoop.createLoop(node0, 3339);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = (-2051);
      Node node0 = new Node((-1454));
      Node node1 = new Node((-2051), node0);
      node1.next = node0;
      node1.next = node0;
      node1.next.next = node0;
      Node node2 = new Node((-2051), node1.next.next);
      node0.next = node2;
      CreateAndDetectLoop.detectLoop(node1);
      String[] stringArray0 = new String[1];
      stringArray0[0] = "No loop found";
      // Undeclared exception!
      try { 
        CreateAndDetectLoop.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Node node0 = new Node();
      Node node1 = new Node((-345), node0);
      node0.next = node1;
      node0.value = (-345);
      CreateAndDetectLoop.detectLoop(node0);
      node1.next = node0;
      // Undeclared exception!
      CreateAndDetectLoop.printList(node0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Node node0 = new Node();
      Node node1 = new Node(887);
      node0.next = node1;
      Node node2 = new Node(887, node0);
      CreateAndDetectLoop.detectLoop(node2);
      // Undeclared exception!
      try { 
        CreateAndDetectLoop.createLoop(node0, 887);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Node node0 = new Node(1);
      Node node1 = new Node();
      node0.next = node1;
      node0.value = 2223;
      Node node2 = new Node((-751));
      node0.next = node2;
      CreateAndDetectLoop.createLoop(node0, 1);
      // Undeclared exception!
      CreateAndDetectLoop.printList(node2);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Node node0 = new Node(1252);
      Node node1 = new Node();
      node0.next = node1;
      node0.value = 1252;
      CreateAndDetectLoop.detectLoop(node0);
      CreateAndDetectLoop.createLoop(node1, (-484));
      CreateAndDetectLoop.detectLoop(node1);
      CreateAndDetectLoop createAndDetectLoop0 = new CreateAndDetectLoop();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Node node0 = new Node();
      boolean boolean0 = CreateAndDetectLoop.detectLoop(node0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Node node0 = new Node();
      Node node1 = new Node(2147, node0);
      node1.next = node0;
      Node node2 = new Node();
      Node node3 = new Node(2147);
      node0.next = node3;
      node1.next = node2;
      node1.next = node0;
      node1.next.next = node0;
      // Undeclared exception!
      CreateAndDetectLoop.createLoop(node1, 2147);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Node node0 = new Node();
      Node node1 = new Node(5136, node0);
      CreateAndDetectLoop.printList(node1);
      CreateAndDetectLoop createAndDetectLoop0 = new CreateAndDetectLoop();
      CreateAndDetectLoop.printList(node0);
      String[] stringArray0 = new String[4];
      stringArray0[0] = "l33kh(h*d.Sj&{&.:q?";
      stringArray0[1] = "+eYp~E1n";
      stringArray0[2] = "";
      stringArray0[3] = "com.thealgorithms.datastructures.lists.Node";
      // Undeclared exception!
      try { 
        CreateAndDetectLoop.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Node node0 = new Node();
      Node node1 = new Node(1914, node0);
      node1.value = 1914;
      node1.next = node0;
      node0.next = node1;
      node0.value = 0;
      node1.value = 1914;
      // Undeclared exception!
      CreateAndDetectLoop.createLoop(node0, 0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CreateAndDetectLoop.createLoop((Node) null, (-2303));
      CreateAndDetectLoop.printList((Node) null);
      CreateAndDetectLoop.createLoop((Node) null, 0);
      CreateAndDetectLoop.printList((Node) null);
      CreateAndDetectLoop.createLoop((Node) null, 0);
      CreateAndDetectLoop.detectLoop((Node) null);
      CreateAndDetectLoop createAndDetectLoop0 = new CreateAndDetectLoop();
      CreateAndDetectLoop.createLoop((Node) null, (-2303));
      CreateAndDetectLoop.createLoop((Node) null, (-2303));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = " ";
      // Undeclared exception!
      try { 
        CreateAndDetectLoop.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Node node0 = new Node(851);
      CreateAndDetectLoop.printList(node0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CreateAndDetectLoop.printList((Node) null);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Node node0 = new Node(738, (Node) null);
      // Undeclared exception!
      try { 
        CreateAndDetectLoop.createLoop(node0, 2669);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Node node0 = new Node();
      Node node1 = new Node();
      node0.next = node1;
      boolean boolean0 = CreateAndDetectLoop.detectLoop(node0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      boolean boolean0 = CreateAndDetectLoop.detectLoop((Node) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Node node0 = new Node((-1));
      Node node1 = new Node(0, node0);
      CreateAndDetectLoop.createLoop(node1, (-1));
      assertFalse(node0.equals((Object)node1));
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Node node0 = new Node(1);
      CreateAndDetectLoop.createLoop(node0, 1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CreateAndDetectLoop.createLoop((Node) null, 0);
      boolean boolean0 = CreateAndDetectLoop.detectLoop((Node) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Node node0 = new Node();
      Node node1 = new Node();
      node0.next = node1;
      Node node2 = new Node();
      CreateAndDetectLoop.detectLoop(node0);
      SystemInUtil.addInputLine("");
      node0.next.next = node2;
      node0.next.next = node1;
      CreateAndDetectLoop.detectLoop(node2);
      CreateAndDetectLoop.detectLoop(node0.next);
      // Undeclared exception!
      try { 
        CreateAndDetectLoop.createLoop(node2, 2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        CreateAndDetectLoop.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Node node0 = new Node();
      CreateAndDetectLoop.printList(node0);
      CreateAndDetectLoop createAndDetectLoop0 = new CreateAndDetectLoop();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CreateAndDetectLoop createAndDetectLoop0 = new CreateAndDetectLoop();
      Node node0 = new Node();
      Node node1 = new Node((-1631), node0);
      CreateAndDetectLoop.createLoop(node1, (-1631));
      assertFalse(node0.equals((Object)node1));
  }
}
