/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:26:37 GMT 2022
 */

package com.thealgorithms.datastructures.lists;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.datastructures.lists.Merge_K_SortedLinkedlist;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Merge_K_SortedLinkedlist_ESTest extends Merge_K_SortedLinkedlist_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Merge_K_SortedLinkedlist merge_K_SortedLinkedlist0 = new Merge_K_SortedLinkedlist();
  }
}
