/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 06:12:58 GMT 2022
 */

package com.thealgorithms.misc;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.misc.PalindromePrime;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PalindromePrime_ESTest extends PalindromePrime_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine(".");
      PalindromePrime palindromePrime0 = new PalindromePrime();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "n\"ie4{h>o";
      stringArray0[5] = "";
      stringArray0[6] = "))Qn";
      stringArray0[7] = "ephT\"#u-v7Rx|KB3'?";
      stringArray0[8] = "";
      // Undeclared exception!
      try { 
        PalindromePrime.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PalindromePrime palindromePrime0 = new PalindromePrime();
      // Undeclared exception!
      PalindromePrime.functioning(3042);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PalindromePrime.reverse(1099);
      PalindromePrime.prime((-576));
      PalindromePrime.prime(1099);
      PalindromePrime.functioning(1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PalindromePrime.functioning(10);
      PalindromePrime.prime(0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PalindromePrime.reverse((-2048));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = 0;
      PalindromePrime.prime(0);
      PalindromePrime.reverse(0);
      String[] stringArray0 = null;
      // Undeclared exception!
      try { 
        PalindromePrime.main((String[]) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PalindromePrime.functioning((-759));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PalindromePrime.prime(0);
      PalindromePrime.reverse(0);
      PalindromePrime.functioning(0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      PalindromePrime.functioning(1013);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      PalindromePrime.functioning(997);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PalindromePrime.functioning(0);
      String[] stringArray0 = new String[7];
      stringArray0[1] = "3x:2~/kq[r)";
      stringArray0[2] = "";
      stringArray0[3] = "3x:2~/kq[r)";
      stringArray0[4] = "3x:2~/kq[r)";
      stringArray0[5] = "com.thealgorithms.misc.PalindromePrime";
      SystemInUtil.addInputLine("2\n");
      boolean boolean0 = PalindromePrime.prime(4201);
      assertTrue(boolean0);
      
      stringArray0[6] = "#TC(d.";
      PalindromePrime.main(stringArray0);
      boolean boolean1 = PalindromePrime.prime((-1));
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PalindromePrime palindromePrime0 = new PalindromePrime();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "D</y3Dh*%JOXwA#";
      // Undeclared exception!
      try { 
        PalindromePrime.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
