/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:18:59 GMT 2022
 */

package com.thealgorithms.misc;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.misc.Trie;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Trie_ESTest extends Trie_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Trie trie0 = new Trie();
      // Undeclared exception!
      try { 
        trie0.add((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.misc.Trie", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Trie trie0 = new Trie();
      trie0.add("B)As<%geRZ=Bgi1pV|");
      trie0.add("B)As<%geRZ=Bgi1pV|");
  }
}
