/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 06:17:21 GMT 2022
 */

package com.thealgorithms.strings;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.strings.Isomorphic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Isomorphic_ESTest extends Isomorphic_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = Isomorphic.checkStrings("5`u yXDcL", "5`u yXDcL");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = Isomorphic.checkStrings("U^A{o#cN", "_tuJtBu!=w");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Isomorphic.checkStrings((String) null, "v@r|kl{pK4l\nes6o(v");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.strings.Isomorphic", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      boolean boolean0 = Isomorphic.checkStrings("v@r|kl{pK4l\nes6o(v", "v@r|kl{pK4l\nes6o(v");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      boolean boolean0 = Isomorphic.checkStrings("t2*qpIE))'?n", "1$\"5zWb~K]!");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      boolean boolean0 = Isomorphic.checkStrings("com.thealgorithms.strings.Isomorphic", "");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Isomorphic isomorphic0 = new Isomorphic();
  }
}
