/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 06:25:26 GMT 2022
 */

package com.thealgorithms.strings;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.strings.Lower;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Lower_ESTest extends Lower_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = Lower.toLowerCase("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Lower.toLowerCase((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.strings.Lower", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = Lower.toLowerCase("abcABC");
      assertEquals("abcabc", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = Lower.toLowerCase("ABC123");
      assertEquals("abc123", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Lower.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Lower lower0 = new Lower();
  }
}
