/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:20:41 GMT 2022
 */

package com.thealgorithms.conversions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.conversions.OctalToHexadecimal;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OctalToHexadecimal_ESTest extends OctalToHexadecimal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = OctalToHexadecimal.decimalToHex((-1165));
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = OctalToHexadecimal.octToDec("^%4{a4/`6}");
      assertEquals(1757727357, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        OctalToHexadecimal.octToDec((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.conversions.OctalToHexadecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = OctalToHexadecimal.decimalToHex(17);
      assertEquals("11", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = OctalToHexadecimal.octToDec("com.thealgorithms.conversions.OctalToHexadecimal");
      assertEquals((-150064380), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = OctalToHexadecimal.octToDec("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = OctalToHexadecimal.decimalToHex(0);
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SystemInUtil.addInputLine("?Vd~C");
      String[] stringArray0 = new String[15];
      OctalToHexadecimal.main(stringArray0);
      assertEquals(15, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      String[] stringArray0 = new String[15];
      // Undeclared exception!
      try { 
        OctalToHexadecimal.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      OctalToHexadecimal octalToHexadecimal0 = new OctalToHexadecimal();
  }
}
