/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:35:08 GMT 2022
 */

package com.thealgorithms.conversions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.conversions.OctalToDecimal;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OctalToDecimal_ESTest extends OctalToDecimal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("-3");
      OctalToDecimal.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = OctalToDecimal.convertOctalToDecimal("0");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = OctalToDecimal.convertOctalToDecimal("3");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      try { 
        OctalToDecimal.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = OctalToDecimal.convertOctalToDecimal("u\"g={1iG1)TC");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[12];
      SystemInUtil.addInputLine("y[C0i$s}7>eQSE[");
      OctalToDecimal.main(stringArray0);
      assertEquals(12, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      OctalToDecimal octalToDecimal0 = new OctalToDecimal();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[8];
      SystemInUtil.addInputLine("3");
      OctalToDecimal.main(stringArray0);
      assertEquals(8, stringArray0.length);
  }
}
