/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 03:42:59 GMT 2022
 */

package com.thealgorithms.datastructures.hashmap.hashing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HashMapCuckooHashing_ESTest extends HashMapCuckooHashing_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int int0 = 5053;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5053);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(5053);
      hashMapCuckooHashing0.deleteKeyFromHashTable(5053);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      int int1 = 0;
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable(5053);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key 5053 already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5053);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(5053);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.deleteKeyFromHashTable(5053);
      hashMapCuckooHashing0.findKeyInTable(0);
      hashMapCuckooHashing0.insertKey2HashTable(5053);
      hashMapCuckooHashing0.getNumberOfKeysInTable();
      hashMapCuckooHashing0.checkLoadFactor();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5052);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.checkLoadFactor();
      // Undeclared exception!
      hashMapCuckooHashing0.isEmpty();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1635);
      hashMapCuckooHashing0.insertKey2HashTable(1635);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.hashFunction2(0);
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.findKeyInTable(0);
      hashMapCuckooHashing0.hashFunction2((-3793));
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.isEmpty();
      hashMapCuckooHashing0.deleteKeyFromHashTable(0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = 2;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(2);
      hashMapCuckooHashing0.insertKey2HashTable(2);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.deleteKeyFromHashTable(2);
      hashMapCuckooHashing0.checkTableContainsKey(1120);
      hashMapCuckooHashing0.isFull();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable((-516));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key -516 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5053);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(5053);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.findKeyInTable(0);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(5053);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = 5013;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5013);
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.isFull();
      // Undeclared exception!
      hashMapCuckooHashing0.findKeyInTable(5013);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = 12;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(12);
      hashMapCuckooHashing0.insertKey2HashTable(12);
      hashMapCuckooHashing0.isFull();
      int int1 = 0;
      hashMapCuckooHashing0.deleteKeyFromHashTable(12);
      hashMapCuckooHashing0.isFull();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable((-516));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key -516 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5053);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(5053);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.findKeyInTable(0);
      hashMapCuckooHashing0.findKeyInTable(0);
      hashMapCuckooHashing0.getNumberOfKeysInTable();
      hashMapCuckooHashing0.hashFunction2(2);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5053);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(3291);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.findKeyInTable(0);
      hashMapCuckooHashing0.insertKey2HashTable(5053);
      hashMapCuckooHashing0.getNumberOfKeysInTable();
      hashMapCuckooHashing0.hashFunction2(3);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1635);
      hashMapCuckooHashing0.insertKey2HashTable(1635);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.hashFunction2((-3793));
      hashMapCuckooHashing0.isEmpty();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key 0 already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(2377);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.hashFunction2((-647));
      hashMapCuckooHashing0.checkTableContainsKey((-2595));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(237);
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(Integer.MIN_VALUE);
      hashMapCuckooHashing0.isEmpty();
      hashMapCuckooHashing0.insertKey2HashTable((-1));
      hashMapCuckooHashing0.checkTableContainsKey((-1));
      hashMapCuckooHashing0.insertKey2HashTable(1352);
      hashMapCuckooHashing0.getNumberOfKeysInTable();
      hashMapCuckooHashing0.hashFunction1(3172);
      hashMapCuckooHashing0.checkTableContainsKey((-2484));
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable((-3090));
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable((-151));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key -151 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int int0 = 4009;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(4009);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      // Undeclared exception!
      hashMapCuckooHashing0.displayHashtable();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      int int0 = 2652;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(2652);
      hashMapCuckooHashing0.insertKey2HashTable(2652);
      hashMapCuckooHashing0.findKeyInTable(2652);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(2652);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int int0 = 2426;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(2426);
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.isEmpty();
      hashMapCuckooHashing0.isEmpty();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      // Undeclared exception!
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(0);
      hashMapCuckooHashing0.isEmpty();
      hashMapCuckooHashing0.displayHashtable();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.hashFunction1(516);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(4058);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.insertKey2HashTable(4058);
      hashMapCuckooHashing0.displayHashtable();
      int int0 = 1669;
      hashMapCuckooHashing0.insertKey2HashTable(1669);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.insertKey2HashTable((-1237));
      int int1 = (-4323);
      hashMapCuckooHashing0.hashFunction1((-4323));
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable((-4323));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key -4323 already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(115);
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.hashFunction2(1097);
      hashMapCuckooHashing0.insertKey2HashTable(1097);
      hashMapCuckooHashing0.displayHashtable();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(1097);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(0);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.checkTableContainsKey(0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      int int0 = 924;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(924);
      hashMapCuckooHashing0.displayHashtable();
      int int1 = 1;
      hashMapCuckooHashing0.isFull();
      int int2 = (-740);
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.insertKey2HashTable((-740));
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable((-740));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.deleteKeyFromHashTable(0);
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.hashFunction1(0);
      hashMapCuckooHashing0.hashFunction2(1);
      hashMapCuckooHashing0.displayHashtable();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Table is empty
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(237);
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(Integer.MIN_VALUE);
      hashMapCuckooHashing0.isEmpty();
      hashMapCuckooHashing0.insertKey2HashTable((-1));
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.insertKey2HashTable(1352);
      hashMapCuckooHashing0.getNumberOfKeysInTable();
      hashMapCuckooHashing0.hashFunction1(3172);
      hashMapCuckooHashing0.checkTableContainsKey((-2484));
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable((-3090));
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable((-151));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key -151 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(5);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.hashFunction1(2708);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key 0 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1);
      hashMapCuckooHashing0.insertKey2HashTable((-3468));
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key 1 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1);
      hashMapCuckooHashing0.checkTableContainsKey(1);
      hashMapCuckooHashing0.hashFunction1(1570);
      hashMapCuckooHashing0.displayHashtable();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Table is empty
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(0);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.hashFunction2(0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      int int0 = 0;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(0);
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable(0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      int int0 = 0;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(0);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.checkLoadFactor();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable((-312));
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(2529);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.checkTableContainsKey(0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1428);
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.insertKey2HashTable(1428);
      hashMapCuckooHashing0.findKeyInTable(1428);
      hashMapCuckooHashing0.findKeyInTable(1428);
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.findKeyInTable(1428);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(1428);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5053);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(3291);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.findKeyInTable(0);
      hashMapCuckooHashing0.getNumberOfKeysInTable();
      hashMapCuckooHashing0.hashFunction2(2);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1806);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(40);
      int int0 = Integer.MIN_VALUE;
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(Integer.MIN_VALUE);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key -2147483648 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(0);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.getNumberOfKeysInTable();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.isEmpty();
      int int0 = 1;
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(1);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1635);
      hashMapCuckooHashing0.insertKey2HashTable(1635);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      int int0 = 0;
      hashMapCuckooHashing0.hashFunction2(0);
      int int1 = (-3793);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key 0 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1);
      hashMapCuckooHashing0.checkLoadFactor();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Table is empty
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      int int0 = Integer.MIN_VALUE;
      HashMapCuckooHashing hashMapCuckooHashing0 = null;
      try {
        hashMapCuckooHashing0 = new HashMapCuckooHashing(Integer.MIN_VALUE);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      int int0 = 709;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(709);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.deleteKeyFromHashTable(0);
      hashMapCuckooHashing0.getNumberOfKeysInTable();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.hashFunction2((-366));
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key 1 already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1791);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.checkLoadFactor();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable(Integer.MIN_VALUE);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key -2147483648 already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(622);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Table is empty
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(2092);
      hashMapCuckooHashing0.insertKey2HashTable(2092);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(2299);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(2299);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Table is empty
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1);
      hashMapCuckooHashing0.insertKey2HashTable((-394));
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.checkTableContainsKey(2121);
      hashMapCuckooHashing0.hashFunction1(2121);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      int int0 = 0;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(0);
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.checkLoadFactor();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable((-312));
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      int int0 = (-3716);
      HashMapCuckooHashing hashMapCuckooHashing0 = null;
      try {
        hashMapCuckooHashing0 = new HashMapCuckooHashing((-3716));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5053);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(5053);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.deleteKeyFromHashTable(5053);
      hashMapCuckooHashing0.findKeyInTable(0);
      hashMapCuckooHashing0.insertKey2HashTable(5053);
      hashMapCuckooHashing0.getNumberOfKeysInTable();
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(5053);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(5053);
      hashMapCuckooHashing0.insertKey2HashTable(0);
      int int0 = 0;
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(5053);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(131);
      hashMapCuckooHashing0.isFull();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Table is empty
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1635);
      hashMapCuckooHashing0.insertKey2HashTable(1635);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      int int0 = 0;
      hashMapCuckooHashing0.hashFunction2(0);
      hashMapCuckooHashing0.checkLoadFactor();
      int int1 = (-3793);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key 0 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1635);
      hashMapCuckooHashing0.insertKey2HashTable(1635);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable(5021);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key 5021 already inside, no duplicates allowed
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(0);
      hashMapCuckooHashing0.deleteKeyFromHashTable(0);
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.hashFunction1(0);
      hashMapCuckooHashing0.hashFunction2(1);
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      int int0 = 2;
      hashMapCuckooHashing0.checkTableContainsKey(2);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Table is empty
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1);
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      assertEquals(0, hashMapCuckooHashing0.getNumberOfKeysInTable());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(1);
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.reHashTableIncreasesTableSize();
      hashMapCuckooHashing0.isFull();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.deleteKeyFromHashTable(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Table is empty
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(237);
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.checkLoadFactor();
      hashMapCuckooHashing0.displayHashtable();
      hashMapCuckooHashing0.insertKey2HashTable(Integer.MIN_VALUE);
      hashMapCuckooHashing0.isEmpty();
      hashMapCuckooHashing0.insertKey2HashTable((-1));
      hashMapCuckooHashing0.isFull();
      hashMapCuckooHashing0.insertKey2HashTable(1352);
      hashMapCuckooHashing0.getNumberOfKeysInTable();
      hashMapCuckooHashing0.hashFunction1(3172);
      hashMapCuckooHashing0.checkTableContainsKey((-2484));
      hashMapCuckooHashing0.displayHashtable();
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.findKeyInTable((-151));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Key -151 not found in table
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      int int0 = 0;
      HashMapCuckooHashing hashMapCuckooHashing0 = new HashMapCuckooHashing(0);
      // Undeclared exception!
      try { 
        hashMapCuckooHashing0.insertKey2HashTable(0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing", e);
      }
  }
}
