/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 04:46:00 GMT 2022
 */

package com.thealgorithms.datastructures.graphs;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.datastructures.graphs.Graphs;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Graphs_ESTest extends Graphs_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Graphs.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Graphs graphs0 = new Graphs();
  }
}
