/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:34:45 GMT 2022
 */

package com.thealgorithms.datastructures.graphs;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.datastructures.graphs.KahnsAlgorithm;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KahnsAlgorithm_ESTest extends KahnsAlgorithm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      KahnsAlgorithm.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      KahnsAlgorithm kahnsAlgorithm0 = new KahnsAlgorithm();
  }
}
