/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:34:40 GMT 2022
 */

package com.thealgorithms.datastructures.trees;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.datastructures.trees.CreateBSTFromSortedArray;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CreateBSTFromSortedArray_ESTest extends CreateBSTFromSortedArray_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CreateBSTFromSortedArray createBSTFromSortedArray0 = new CreateBSTFromSortedArray();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[2];
      CreateBSTFromSortedArray.main(stringArray0);
      assertEquals(2, stringArray0.length);
  }
}
