/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 03:21:02 GMT 2022
 */

package com.thealgorithms.datastructures.trees;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.datastructures.trees.RedBlackBST;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RedBlackBST_ESTest extends RedBlackBST_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("00");
      SystemInUtil.addInputLine("9 s2");
      RedBlackBST redBlackBST0 = new RedBlackBST();
      // Undeclared exception!
      try { 
        redBlackBST0.insertDemo();
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SystemInUtil.addInputLine("Z|I^RP.U)NN&~%?`R");
      RedBlackBST redBlackBST0 = new RedBlackBST();
      // Undeclared exception!
      try { 
        redBlackBST0.deleteDemo();
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SystemInUtil.addInputLine("00");
      SystemInUtil.addInputLine("00");
      SystemInUtil.addInputLine("00");
      SystemInUtil.addInputLine("00");
      SystemInUtil.addInputLine("00");
      SystemInUtil.addInputLine("00");
      SystemInUtil.addInputLine("00");
      SystemInUtil.addInputLine("00");
      RedBlackBST redBlackBST0 = new RedBlackBST();
      // Undeclared exception!
      try { 
        redBlackBST0.insertDemo();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SystemInUtil.addInputLine("+3");
      RedBlackBST redBlackBST0 = new RedBlackBST();
      redBlackBST0.deleteDemo();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RedBlackBST redBlackBST0 = new RedBlackBST();
      // Undeclared exception!
      try { 
        redBlackBST0.deleteDemo();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
