/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:38:08 GMT 2022
 */

package com.thealgorithms.datastructures.graphs;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.datastructures.graphs.ConnectedComponent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConnectedComponent_ESTest extends ConnectedComponent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConnectedComponent connectedComponent0 = new ConnectedComponent();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[2];
      ConnectedComponent.main(stringArray0);
      assertEquals(2, stringArray0.length);
  }
}
