/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:27:26 GMT 2022
 */

package com.thealgorithms.conversions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.conversions.AnytoAny;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AnytoAny_ESTest extends AnytoAny_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("8");
      String[] stringArray0 = new String[1];
      SystemInUtil.addInputLine("8");
      SystemInUtil.addInputLine("8");
      AnytoAny.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        AnytoAny.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[2];
      SystemInUtil.addInputLine("com.thealgorithms.conversions.AnytoAny");
      // Undeclared exception!
      try { 
        AnytoAny.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SystemInUtil.addInputLine("48");
      String[] stringArray0 = new String[3];
      SystemInUtil.addInputLine("48");
      SystemInUtil.addInputLine("48");
      AnytoAny.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      String[] stringArray0 = new String[7];
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("1");
      // Undeclared exception!
      AnytoAny.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AnytoAny anytoAny0 = new AnytoAny();
  }
}
