/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 06:04:30 GMT 2022
 */

package com.thealgorithms.strings;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.strings.longestNonRepeativeSubstring;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class longestNonRepeativeSubstring_ESTest extends longestNonRepeativeSubstring_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = longestNonRepeativeSubstring.lengthOfLongestSubstring("(B9#4}zKdN#/ce}");
      assertEquals(11, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = longestNonRepeativeSubstring.lengthOfLongestSubstring("ZV//<XXv");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = longestNonRepeativeSubstring.lengthOfLongestSubstring("@+svp7Hc++");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = longestNonRepeativeSubstring.lengthOfLongestSubstring("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        longestNonRepeativeSubstring.lengthOfLongestSubstring((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.strings.longestNonRepeativeSubstring", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = longestNonRepeativeSubstring.lengthOfLongestSubstring("pw$FFH^\"P/>");
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int int0 = longestNonRepeativeSubstring.lengthOfLongestSubstring("j}(;'<0n0vnn:#5");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int int0 = longestNonRepeativeSubstring.lengthOfLongestSubstring("com.thealgorithms.strings.longestNonRepeativeSubstring");
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      longestNonRepeativeSubstring longestNonRepeativeSubstring0 = new longestNonRepeativeSubstring();
  }
}
